alert:
  type: mail
spring:
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: xxxxxxx@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: xxxxxxxxxxx
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
file:
  store:
    type: minio
    dir: /data/files/
    url: http://172.23.16.63:9000/
    access: hufY76YgdgjGHGlOoiK
    secret: Hyhdygyf654GY5r8tigyYgyhefbjfrklgrjogjHtd
